//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью wsdl, версия=4.8.3928.0.
// 
namespace Lab_4_WebForm
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Web.Services.WebServiceAttribute(Namespace = "http://GEA/")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "SimplexSoap", Namespace = "http://GEA/")]
    public class SimplexClient : System.Web.Services.WebService
    {

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://GEA/Sum_1", RequestElementName = "Sum_1", RequestNamespace = "http://GEA/", ResponseElementName = "Sum_1Response", ResponseNamespace = "http://GEA/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Sum_1Result")]
        public int Add(int x, int y)
        {
            return x + y;
        }

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://GEA/Sum_2", RequestElementName = "Sum_2", RequestNamespace = "http://GEA/", ResponseElementName = "Sum_2Response", ResponseNamespace = "http://GEA/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Sum_2Result")]
        public string Concat(string s, double d)
        {
            return s + d.ToString();
        }

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://GEA/Sum_3", RequestElementName = "Sum_3", RequestNamespace = "http://GEA/", ResponseElementName = "Sum_3Response", ResponseNamespace = "http://GEA/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Sum_3Result")]
        public A Sum(A a1, A a2)
        {
            A a3 = new A();
            a3.s = String.Concat(a1.s, a2.s);
            a3.k = a1.k + a2.k;
            a3.f = a1.f + a2.f;

            return a3;
        }

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://GEA/Sum_4", RequestElementName = "Sum_4", RequestNamespace = "http://GEA/", ResponseElementName = "Sum_4Response", ResponseNamespace = "http://GEA/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Sum_4Result")]
        public int Adds(int x, int y)
        {
            return x + y;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://GEA/")]
    public partial class A
    {

        private string sField;

        private int kField;

        private float fField;

        /// <remarks/>
        public string s
        {
            get
            {
                return this.sField;
            }
            set
            {
                this.sField = value;
            }
        }

        /// <remarks/>
        public int k
        {
            get
            {
                return this.kField;
            }
            set
            {
                this.kField = value;
            }
        }

        /// <remarks/>
        public float f
        {
            get
            {
                return this.fField;
            }
            set
            {
                this.fField = value;
            }
        }
    }
}
